name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and deploy'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Clear deploy branch
        run: |
          git checkout ${{ github.event.inputs.branch }}
          git pull origin ${{ github.event.inputs.branch }}
          git rm -r .
          git commit -am "Clear deploy branch"
          git push

      - name: Copy build output to deploy branch
        run: |
          cp -r build/* .
          git add .
          git commit -m "Add build output"
          git push
